In [2]:
import torch
import torch.nn as nn

In [25]:
embedding = torch.nn.Embedding(10, 2) # (size of the dictionary of embeddings, the size of each embedding vector )
embedding # this shape is also the shape of learnable weights 

Embedding(10, 2)

In [23]:
embedding.weight, embedding.weight.shape

(Parameter containing:
 tensor([[ 0.7597,  1.7374],
         [ 0.1892, -1.6730],
         [ 0.5094,  1.4136],
         [ 0.4732,  0.0168],
         [ 0.2382, -0.8524],
         [-0.0880,  0.3129],
         [-2.2461, -0.6322],
         [ 0.3533,  0.0156],
         [-2.5434, -0.6940],
         [-0.0194,  1.5078]], requires_grad=True), torch.Size([10, 2]))

In [10]:
input = torch.arange(0, 6).reshape(3, 2).long() # input must be LongTensor, get 2 group each batch, each group has 2 words
input, input.shape # (the size of batch, the number of word in each batch)

(tensor([[0, 1],
         [2, 3],
         [4, 5]]), torch.Size([3, 2]))

In [18]:
output = embedding(input)
output, output.shape # (input shape, embedding_dim)

(tensor([[[ 0.0322,  2.9780],
          [-0.8769,  0.6011]],
 
         [[ 0.0030, -0.2877],
          [-0.4961,  0.6808]],
 
         [[ 2.1389, -0.4579],
          [ 1.6143, -0.3068]]], grad_fn=<EmbeddingBackward>),
 torch.Size([3, 2, 2]))

(Parameter containing:
 tensor([[ 0.0322,  2.9780],
         [-0.8769,  0.6011],
         [ 0.0030, -0.2877],
         [-0.4961,  0.6808],
         [ 2.1389, -0.4579],
         [ 1.6143, -0.3068],
         [-0.4207, -0.9469],
         [-0.8625,  0.6693],
         [ 0.5372,  1.4874],
         [-0.7305,  2.4571]], requires_grad=True), torch.Size([10, 2]))